# Generated by Django 2.1.5 on 2019-02-10 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_auto_20190210_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 10, 17, 56, 36, 239657, tzinfo=utc)),
        ),
    ]
