# Generated by Django 2.1.5 on 2019-02-11 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_auto_20190210_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 11, 8, 11, 47, 300954, tzinfo=utc)),
        ),
    ]
