# Generated by Django 2.1.5 on 2019-02-13 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_auto_20190211_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 10, 31, 18, 365860, tzinfo=utc)),
        ),
    ]
