# Generated by Django 2.1.5 on 2019-02-13 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_auto_20190213_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 11, 15, 5, 72873, tzinfo=utc)),
        ),
    ]
