# Generated by Django 2.1.5 on 2019-02-13 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_auto_20190213_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 11, 35, 31, 974395, tzinfo=utc)),
        ),
    ]
