# Generated by Django 2.1.5 on 2019-02-14 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_auto_20190213_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 9, 45, 3, 721672, tzinfo=utc)),
        ),
    ]
