# Generated by Django 2.1.5 on 2019-02-15 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0028_auto_20190215_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 15, 16, 37, 59, 160523, tzinfo=utc)),
        ),
    ]
