# Generated by Django 2.1.5 on 2019-02-15 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0029_auto_20190215_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 15, 16, 41, 29, 906273, tzinfo=utc)),
        ),
    ]
