# Generated by Django 2.1.7 on 2019-04-01 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0030_auto_20190215_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 13, 58, 19642, tzinfo=utc)),
        ),
    ]
