# Generated by Django 2.2 on 2019-04-22 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0031_auto_20190401_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 11, 16, 42, 248575, tzinfo=utc)),
        ),
    ]
