# Generated by Django 2.2 on 2019-04-22 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0032_auto_20190422_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 11, 19, 20, 375118, tzinfo=utc)),
        ),
    ]
