# Generated by Django 2.2 on 2019-04-22 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0033_auto_20190422_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
