# Generated by Django 2.1.5 on 2019-02-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('protein', models.IntegerField(default=0)),
                ('carbohidrate', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='food', to='nutrition.Food')),
                ('food_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='food_nutrition', to='nutrition.FoodCategory')),
            ],
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='food_category',
            field=models.ForeignKey(choices=[('c', 'Carne'), ('p', 'Pescado'), ('f', 'Fruta'), ('v', 'Verdura'), ('l', 'Lacteo'), ('b', 'Bebida')], help_text='Tipo de alimento', max_length=1, on_delete=django.db.models.deletion.CASCADE, to='nutrition.Nutrition'),
        ),
    ]
