# Generated by Django 2.1.5 on 2019-02-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='food_category',
        ),
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='food_name', to='nutrition.FoodCategory'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(default='', help_text='Tipo de alimento', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='', help_text='Alimento', max_length=100),
        ),
    ]
