# Generated by Django 2.1.5 on 2019-02-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20190215_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='food_name', to='nutrition.FoodCategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='food', to='nutrition.Food', unique=True),
        ),
    ]
