# Generated by Django 2.1.5 on 2019-02-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20190216_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='food',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='food_category',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='food_category_name', to='nutrition.FoodCategory', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
