# Generated by Django 2.1.5 on 2019-02-14 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20190214_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 10, 0, 5, 210987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 10, 0, 5, 210025, tzinfo=utc)),
        ),
    ]
