# Generated by Django 2.1.5 on 2019-02-14 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_auto_20190214_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 10, 2, 18, 684885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 10, 2, 18, 683886, tzinfo=utc)),
        ),
    ]
