# Generated by Django 2.1.5 on 2019-03-19 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0028_auto_20190215_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 10, 37, 19, 92570, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 10, 37, 19, 91611, tzinfo=utc)),
        ),
    ]
