# Generated by Django 2.1.5 on 2019-03-19 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0029_auto_20190319_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 10, 40, 43, 756548, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 10, 40, 43, 755569, tzinfo=utc)),
        ),
    ]
