# Generated by Django 2.1.5 on 2019-03-19 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0030_auto_20190319_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 19, 41, 52, 292555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 19, 41, 52, 291567, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('machine', 'date')},
        ),
    ]
