# Generated by Django 2.1.5 on 2019-03-26 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0032_auto_20190323_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('date', models.DateField(default=datetime.datetime(2019, 3, 26, 11, 42, 15, 673454, tzinfo=utc))),
                ('weight', models.IntegerField(max_length=10)),
                ('chest', models.IntegerField(max_length=10)),
                ('biceps', models.IntegerField(max_length=10)),
                ('waist', models.IntegerField(max_length=10)),
                ('quadricep', models.IntegerField(max_length=10)),
                ('gastrocnemius', models.IntegerField(max_length=10)),
                ('muscle_mass', models.IntegerField(max_length=10)),
                ('muscle_fat', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 11, 42, 15, 674872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 11, 42, 15, 672963, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='userimages',
            name='weight_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.WeightData'),
        ),
    ]
