# Generated by Django 2.1.5 on 2019-03-26 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0033_auto_20190326_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimages',
            name='weight_data',
        ),
        migrations.AddField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='gym.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 12, 47, 3, 937697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 12, 47, 3, 936399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 12, 47, 3, 935935, tzinfo=utc)),
        ),
    ]
