# Generated by Django 2.1.5 on 2019-03-26 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0034_auto_20190326_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 0, 32, 276896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 0, 32, 275582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 0, 32, 275105, tzinfo=utc)),
        ),
    ]
