# Generated by Django 2.1.5 on 2019-03-26 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0035_auto_20190326_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 7, 4, 310864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 7, 4, 309569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 18, 7, 4, 309109, tzinfo=utc)),
        ),
    ]
