# Generated by Django 2.1.5 on 2019-03-27 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0036_auto_20190326_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 8, 23, 49, 880132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 8, 23, 49, 878806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='gym.UserProfile'),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 8, 23, 49, 878349, tzinfo=utc)),
        ),
    ]
