# Generated by Django 2.1.7 on 2019-04-01 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0040_auto_20190329_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 15, 11, 148696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 15, 11, 147534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 15, 11, 147079, tzinfo=utc)),
        ),
    ]
