# Generated by Django 2.1.7 on 2019-04-01 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0042_auto_20190401_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')])),
                ('from_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_people', to='gym.UserProfile')),
                ('to_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_people', to='gym.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 15, 34, 731935, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 15, 34, 719416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 15, 34, 718964, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_to', through='gym.Relationship', to='gym.UserProfile'),
        ),
    ]
