# Generated by Django 2.1.7 on 2019-04-11 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0045_auto_20190409_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 10, 3, 39, 537954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 10, 3, 39, 525398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 10, 3, 39, 524943, tzinfo=utc)),
        ),
    ]
