# Generated by Django 2.2 on 2019-04-22 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0047_auto_20190422_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 11, 19, 20, 374022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 11, 19, 20, 372261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 11, 19, 20, 371583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
