# Generated by Django 2.2 on 2019-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0050_auto_20190422_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='gym.Relationship', to='gym.UserProfile'),
        ),
    ]
